export * from './columnsActions';
export * from './cardActions';
export * from './popupAction'

export const CONSTS = {
  ADD_COLUMN: 'ADD_COLUMN',
  ADD_CARD: 'ADD_CARD',
  EDIT_COLUMN_TITLE: 'EDIT_COLUMN_TITLE',
  DELETE_COLUMN: 'DELETE_COLUMN',
  EDIT_CARD_TITLE: 'EDIT_CARD_TITLE',
  DELETE_CARD: 'DELETE_CARD',
  OPEN_POPUP: 'OPEN_POPUP',
  CLOSE_POPUP: 'CLOSE_POPUP',
  SAVE_DATE: 'SAVE_DATE',
  CHANGE_COLOR: 'CHANGE_COLOR',
  ADD_DESCRIPTION: 'ADD_DESCRIPTION',
  DRAG_HAPPENED: 'DRAG_HAPPENED'
};